### ISSUE TITLE
Rewrite to stateless functional component

### ISSUE THREAD

**Issue by misund** [soldotno/react-component-empty#2]
Since React 0.14 it's been possible to write components as pure functions. That would spare us some overhead, we wouldn't even need to depend on React.

The downside is that this component no longer would be compatible with React < 0.14. If you're still using 0.13, though... you should probably upgrade.

**Want to learn more about stateless functional components?**
- Introductory blog post: [Stateless Functional Components in React 0.14](https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d)
- ESlint rule [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/30af256d432a1f8b7bddfcc5b4a75d3a4662e553/docs/rules/prefer-stateless-function.md)

**Comment by otakustay** [comment]
I'd like to create a pull request if this repo is still under maintenance, also `react` should not be a dependency, it should be a peer dependency

**Comment by misund** [comment]
I'll have a look at your pull request :)

**Comment by misund** [comment]
Fixed in #3, released in 2.0.0
